"""add_category_id_to_maintenance_assets

Revision ID: a8d6374d236d
Revises: 115019e8fea4
Create Date: 2025-11-19 14:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a8d6374d236d'
down_revision: Union[str, None] = '115019e8fea4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maintenance_assets', sa.Column('category_id', sa.UUID(), nullable=True))
    op.create_foreign_key(
        'fk_maintenance_assets_category_id',
        'maintenance_assets',
        'maintenance_asset_categories',
        ['category_id'],
        ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_maintenance_assets_category_id', 'maintenance_assets', type_='foreignkey')
    op.drop_column('maintenance_assets', 'category_id')
    # ### end Alembic commands ###
